language: go
go_import_path: github.com/vimeo/galaxycache

os: linux
dist: trusty

script:
  - go test ./...

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - master

cache:
  directories:
    - $GOPATH/pkg
